# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFxoF2ZsVXrvtLjk7kg-wkyFYQWp37Zd
"""

import cv2
from google.colab.patches import cv2_imshow
import os

test = [] 

testing_path = '/content/drive/My Drive/Test'

for images in os.listdir(testing_path):
    img_path = os.path.join(testing_path, images)

    img = cv2.imread(img_path)
    resize = cv2.resize(img, (64, 64))

    cv2_imshow(resize)

    test.append(resize)

import numpy as np

test = np.array(test, dtype = 'float32') / 255
test = test.reshape(test.shape[0], 64, 64, 3)

import tensorflow as tf
from tensorflow import keras
from keras.models import load_model

classify = load_model('/content/drive/My Drive/carbus.h5')

classify.summary()

y = classify.predict(test)
for elements in y:
    if elements[0] > 0.5:
        print('bus')
    elif elements[1]>0.5:
        print('car')